
#----------Instillinger: Boks på toppen av side----------------------------------------------------------------------
bilde: https://github.com/uit-econ/hovedside/blob/main/assets/img/Sok-1004.jpg?raw=true #Emnebilde
name: Sok-1004 Økonomiske emner med programmering #Emnetittel
semester: Høst 2021
webadresse: https://uit-sok-1004-h21.github.io/


#--------------Avanserte instillinger---------------------------------------------------------------------
topbox-farge: 00617f

contentbox-farge: ffff;
contentbox-skygge: 0px 0px 100px 0px rgba(50, 50, 50, 1)

bakgrunn: https://github.com/uit-sok-1003-h21/emneside-alt/blob/main/assets/img/emneside-bakgrunn1.jpg?raw=true
bakgrunn-farge: 

#Farge tekst
primaerfarge: 007396 #Farge overskrifter
sekundaerfarge: #Farge generell tekst
linkfarge: f2a900 #Farge linker

uitlogo: https://github.com/uit-sok-1003-h21/emneside-alt/blob/main/assets/img/UiT_Logo_Bok_Hvit.png?raw=true
title: null #Skal stå tom



#-------------IKKE SLETT---------------------------------------------------------------------
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
   auto_ids: true
